"""
IPS Dated Sites — documentation generator
=========================================

Writes docs/*.md. Nothing here is hand-maintained prose about structure:
every class, property, namespace, figure constant and query is read out of
the code at generation time, so a change to the export shows up in the
documentation on the next run rather than drifting away from it.

Three sources are combined:

    ips_rdf_export   CLASSES, OBJ_PROPS, DATA_PROPS, PREFIXES,
                     FIGURE_CONSTANTS, EXCLUDED_DATEMAX, KEY_ALGORITHM
    ips_sparql       the SPARQL queries, verbatim
    ips_docs_text    the English prose, which also feeds rdfs:comment@en

The generator FAILS if a class or property exists in the code without an
entry in TERM_DOCS. Adding a property therefore forces a decision about
how it is described, instead of letting it appear undocumented.

Run via  python py/main.py  (step 5), or on its own:

    python py/make_docs.py --out docs
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from html import escape, unescape
from pathlib import Path

import ips_docs_text as T
import make_diagrams as D
import ips_rdf_export as X
import ips_render as R
import ips_sparql as Q

ROOT = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
def local(term) -> str:
    """Local name of a URIRef."""
    s = str(term)
    return s.split("#")[-1] if "#" in s else s.rsplit("/", 1)[-1]


def qname(term) -> str:
    """Prefixed name, using the export's own prefix map."""
    s = str(term)
    for pfx, ns in X.PREFIXES.items():
        if s.startswith(str(ns)):
            return f"{pfx}:{s[len(str(ns)):]}"
    return f"<{s}>"


def doc(term) -> str:
    return T.TERM_DOCS.get(local(term), "")


def subclass_paths(cls, direct: dict, seen: tuple = ()) -> list[list]:
    """
    Every path from a class up to one that has no superclass of its own.

    Branches where a class has more than one superclass, so
    lado:FindspotDating yields two paths — one ending in CIDOC CRM, one in
    OWL-Time. Both are true at once, and showing only the direct parent
    hides exactly the fact the crosswalk is meant to demonstrate.
    """
    sups = direct.get(cls)
    if not sups:
        return [[cls]]
    out = []
    for sup in sorted(sups, key=lambda t: str(t)):
        if sup in seen:            # guard against a cyclic hierarchy
            continue
        for tail in subclass_paths(sup, direct, seen + (cls,)):
            out.append([cls] + tail)
    return out or [[cls]]


def check_coverage() -> list[str]:
    """Every term in the code must be documented."""
    missing = []
    for cls, *_ in X.CLASSES:
        if local(cls) not in T.TERM_DOCS:
            missing.append(f"class {local(cls)}")
    for prop, *_ in X.OBJ_PROPS + X.DATA_PROPS:
        if local(prop) not in T.TERM_DOCS:
            missing.append(f"property {local(prop)}")
    for pfx in X.PREFIXES:
        if pfx not in T.CROSSWALK_NOTES:
            missing.append(f"namespace {pfx}")
    return missing


# Where the links under the diagrams point.
# Relative links work on github.com but not on GitHub Pages: the .mmd
# files are not there at all, because docs/_config.yml excludes them.
# Absolute links work from both contexts.
REPO = "leiza-rse/IPSDatedSites"
BRANCH = "main"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
BLOB_BASE = f"https://github.com/{REPO}/blob/{BRANCH}"

# Diagrams, generated once and handed to both outputs: as .mmd under
# docs/diagrams/ and as an inline block here. One source, two outputs.
_DIAGRAMS: dict[str, str] = {}


def diagram(name: str, caption: str = "") -> str:
    """
    A Mermaid block plus a link to the standalone file.

    github.com renders the block directly. GitHub Pages needs mermaid.js in
    the layout for that; until then the .mmd file is the way out.
    """
    src = _DIAGRAMS.get(name)
    if not src:
        return ""
    cap = f"\n*{caption}*\n" if caption else ""
    jpg = f"{RAW_BASE}/img/diagrams/{name}.jpg"
    svg = f"{RAW_BASE}/img/diagrams/{name}.svg"
    mmd = f"{BLOB_BASE}/docs/diagrams/{name}.mmd"
    return (f"\n```mermaid\n{src}\n```\n{cap}\n"
            f"<sub>[JPG]({jpg}) · [SVG]({svg}) · "
            f"[Mermaid source]({mmd}) — generated, do not edit.</sub>\n")


HEADER = ("<!-- Generated by py/make_docs.py — do not edit by hand.\n"
          "     The structure is read from the code; the prose lives in\n"
          "     py/ips_docs_text.py. Edit those, then re-run the pipeline. -->\n")


def write(out: Path, name: str, body: str) -> Path:
    p = out / name
    p.write_text(HEADER + "\n" + body.rstrip() + "\n", encoding="utf-8")
    return p


# --------------------------------------------------------------------------
def page_index(out: Path) -> Path:
    n_cls = len(X.CLASSES)
    n_obj = len(X.OBJ_PROPS)
    n_dat = len(X.DATA_PROPS)
    body = f"""# Findspot datings as linked data

How the dating of archaeological findspots by samian potters' stamps is
modelled as RDF, and why each decision was taken.

The source is a single query over the Samian Research / IPS database, one
row per findspot. The export turns each row into a small graph built on
CIDOC CRM, OWL-Time, PROV-O and the local LADO vocabulary, and a companion
step reconstructs the published figure from that graph alone using SPARQL.
That reconstruction is the test of the modelling: if a quantity the figure
needs is missing from the graph, the round trip fails rather than quietly
substituting a default.

## Pages

| Page | Contents |
|---|---|
| [Model](model.md) | The three layers, URI strategy, and the treatment of missing values |
| [Vocabulary](vocabulary.md) | The {n_cls} classes and {n_obj + n_dat} properties minted here |
| [Crosswalk](crosswalk.md) | Mapping to CIDOC CRM, OWL-Time, GeoSPARQL, PROV-O, DCAT and SKOS |
| [Statistics](statistics.md) | The formulas behind the intervals, as implemented in SQL |
| [Queries](queries.md) | The SPARQL used to rebuild the figure, and the round-trip check |
| [Bundle](bundle.md) | The standalone file for a triplestore, and why the crosswalk is materialised |
| [Method notes](docu/) | The formulae in longhand, the SQL walkthrough, and where the data come from |

{diagram("architecture", "The pipeline. Everything after the export reads from the graph, never from the CSV — apart from the round-trip check, which compares the two.")}
## The shape of it in one paragraph

A findspot (`lado:Findspot`, beneath `crm:E53_Place`) falls within a
published discovery site. Its dating (`lado:FindspotDating`, beneath both
`crm:E52_Time-Span` and `time:ProperInterval`) hangs off it and carries the
computed interval together with every quantity needed to recompute that
interval. The presentation layer sits apart: a `lado:PlotRow` renders the
dating and carries the whiskers, which the method documentation classes as
visual only. Provenance runs through PROV-O, with the model parameters
stated once on a `prov:Plan` rather than repeated on each row.

## Regenerating

These pages are generated. Running the pipeline rewrites them:

```
python py/main.py
```

Structure comes from the code itself — classes, properties, namespaces,
figure constants and queries are read at generation time. The English
prose lives in `py/ips_docs_text.py`, which also supplies the English
`rdfs:comment` on every term in the ontology, so a definition cannot be
correct in the documentation and stale in the RDF. The generator refuses
to run if a class or property in the code has no entry there.

*{n_cls} classes, {n_obj} object properties and {n_dat} datatype
properties. Undated by design: what these pages describe is the code, which
does not have a date, and the corpus state is recorded in
`data/SNAPSHOT.json`.*
"""
    return write(out, "index.md", body)


# --------------------------------------------------------------------------
def page_model(out: Path) -> Path:
    rows = "\n".join(f"| `{c}` | `{s}` | `{p}` |"
                     for c, s, p in T.COLUMN_MAP)
    consts = "\n".join(
        f"| `lado:{k}` | `{v[0]}` | {T.TERM_DOCS.get(k, '')} |"
        for k, v in X.FIGURE_CONSTANTS.items())
    body = f"""# The model

## Three layers, kept apart

The export separates what is in the world, what we claim about it, and
what the drawing does. The separation is not tidiness for its own sake: it
determines what a SPARQL query picks up.

### 1 — Place and findspot

```
samian:loc_ds_<id>          already published, referenced only
samian:fs_<id>_<hash>       lado:Findspot, crm:P89_falls_within the site
```

The discovery site is not re-minted. `the_id` from the `v_discoverysite`
join is the `dc:identifier` of an already published node, and all 3,879 of
those identifiers match their URI suffix exactly, so the URI can be
constructed directly with no lookup table. This export adds an
`rdfs:label` and, where present, the ancient name and Pleiades identifier;
it does not re-type the node or restate what the published file already
says.

The findspot is new. It exists because a site may carry several findspots
with different dates — Bregenz has four — and hanging four time-spans
directly off one place would lose which is which.

### 2 — The dating

```
samian:ts_<id>_<hash>       lado:FindspotDating
                            -> crm:E52_Time-Span, time:ProperInterval
```

Carries the interval boundaries as OWL-Time instants, and with them every
quantity needed to recompute the interval: sigma, k, the stamp count with
die attribution, the die count, the repetition, and both quality axes. The
identity `width = 2·k·σ` can be verified from the exported figures alone,
which is the point of exporting them.

### 3 — Presentation

```
samian:plotrow_<id>_<hash>  lado:PlotRow, lado:renders the dating
samian:fig_<name>           lado:Figure, constants of the drawing
```

The whiskers live here rather than on the time-span. The method
documentation describes the edge dispersion as visual only — it measures
the scatter of the interval edges, whereas the box is built from the
scatter of the midpoints, so the whisker does not continue the box in any
statistical sense. Attaching it to the dating would assert that it does.

The figure constants sit on a single node instead of being repeated on
each of the rows, because they describe the drawing and not the findspots.

| Constant | Value | Meaning |
|---|---|---|
{consts}

{diagram("relations", "The class skeleton. Boxes outside the three groups belong to OWL-Time and PROV-O: they carry no layer of ours.")}
## Where each column goes

| SQL column | Subject | Predicate |
|---|---|---|
{rows}

{diagram("instance", "One real findspot, read from the generated graph. Change the model and this picture changes with it.")}

### The descent from an interval to a number

{diagram("time-chain", "One boundary, all the way down. The fork at the bottom is the point: the calendar label and the arithmetic position disagree about negative years on purpose.")}

The same thing again, but drawn from the triples themselves rather than
from the model — cut out of the published graph with a `CONSTRUCT` and laid
out by GraphViz, so it can only show what is really there:

![The OWL-Time descent of one interval boundary](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/time-chain.svg)

<sub>[SVG](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/time-chain.svg) · [GraphViz source](https://github.com/leiza-rse/IPSDatedSites/blob/main/img/graphs/time-chain.dot) — cut from the graph by CONSTRUCT, generated, do not edit.</sub>

And the findspot in full:

![One findspot, as modelled](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/findspot.svg)

<sub>[SVG](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/findspot.svg) · [GraphViz source](https://github.com/leiza-rse/IPSDatedSites/blob/main/img/graphs/findspot.dot) — cut from the graph by CONSTRUCT, generated, do not edit.</sub>

### Where a dating comes from

{diagram("provenance", "Two vocabularies say the same thing on purpose: PROV for the provenance world, CIDOC CRM so that a CRM-only consumer sees the method too.")}

![Where one dating comes from](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/provenance.svg)

<sub>[SVG](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/provenance.svg) · [GraphViz source](https://github.com/leiza-rse/IPSDatedSites/blob/main/img/graphs/provenance.dot) — cut from the graph by CONSTRUCT, generated, do not edit.</sub>

Note in the drawn version that `lado:tau` and `lado:referenceLength` end at
the same literal. They both read 20, and identical literals are the same
term in RDF, so the two arrows genuinely land on one node. The shared value
is a coincidence: tau governs how fast the interval tightens as stamps
accumulate, referenceLength is the fixed scale against which qStart and
qEnd are read.
## URIs

Findspot fragments are built as `{X.KEY_ALGORITHM}`. The recipe is
recorded in the graph as `lado:identifierScheme`, because any further
implementation — the planned JavaScript port in particular — must
reproduce it character for character. The Unicode normalisation step is
not cosmetic: if the source yields `ö` once as U+00F6 and once as
`o`+U+0308, the two forms hash differently and one findspot becomes two.
The export checks for collisions and stops rather than silently merging
two findspots that hash alike.

A hash does not make the URI stable. If someone corrects a findspot name,
the hash changes exactly as a readable slug would; it simply changes
invisibly. The readable slug is therefore retained as `skos:notation` so
that a broken link remains diagnosable. There is a live example in the
data: one findspot is recorded as *Böckleareal (descruction layer period
II)*, a typo for *destruction*, sitting in a field from which URIs are
minted.

Time-span URIs are deliberately not versioned. They denote the current
dating of a findspot, so their values change when the source data change.
What is citable is the dated dataset node, which carries `dcterms:issued`
and `owl:versionInfo`; every dating points at it with
`prov:wasDerivedFrom`.

## Missing values

Where a value cannot be computed, the triple is omitted — never replaced
by zero or by 0.5. A fallback of 0.5 would be indistinguishable from a
measured 0.5, which is reachable, and the source query's `COALESCE`
wrappers were removed for that reason.

Omission alone is ambiguous, because under the open-world assumption a
missing triple only means unknown. The export therefore states the absence
explicitly:

```turtle
samian:ts_1000080_a1b2c3 lado:undefinedMeasure lado:qInterval .
```

The figure reads this as its third state: a grey box rather than a
coloured one. If 0.5 were exported instead, anyone reconstructing the
figure from the graph would draw a yellow-green box where the original
draws grey — the fallback would make the figure irreproducible.

In the current data no measure is undefined; all {len(T.COLUMN_MAP)}
mapped columns are populated across every row.
"""
    return write(out, "model.md", body)


# --------------------------------------------------------------------------
def page_vocabulary(out: Path) -> Path:
    cls_rows = []
    for cls, supers, label, _de in X.CLASSES:
        sup = ", ".join(f"`{qname(s)}`" for s in supers)
        cls_rows.append(f"### `{qname(cls)}`\n\n"
                        f"*{label}* — subclass of {sup}\n\n{doc(cls)}\n")

    obj_rows = "\n".join(
        f"| `{qname(p)}` | `{qname(d)}` | `{qname(r)}` | {doc(p)} |"
        for p, d, r, _l, _c in X.OBJ_PROPS)

    def prop_table(props):
        return "\n".join(
            f"| `{qname(p)}` | `{qname(r)}` | {doc(p)} |"
            for p, d, r, _l, _c in props)

    by_domain: dict[str, list] = {}
    for entry in X.DATA_PROPS:
        by_domain.setdefault(qname(entry[1]), []).append(entry)

    sections = []
    for dom in sorted(by_domain):
        sections.append(f"### Properties of `{dom}`\n\n"
                        f"| Property | Range | Definition |\n|---|---|---|\n"
                        f"{prop_table(by_domain[dom])}\n")

    body = f"""# Vocabulary

The classes and properties minted for this export, all in the LADO
namespace `{X.LADO}`. Everything below is read from the code at generation
time; the definitions are the same strings that appear as English
`rdfs:comment` in `rdf/lado_dating_extension.ttl`.

Nothing here duplicates a term that CIDOC CRM or OWL-Time already
provides. Where a standard term exists it is used directly — see the
[crosswalk](crosswalk.md).

## Classes

{chr(10).join(cls_rows)}
## Object properties

| Property | Domain | Range | Definition |
|---|---|---|---|
{obj_rows}

## Datatype properties

{chr(10).join(sections)}
"""
    return write(out, "vocabulary.md", body)


# --------------------------------------------------------------------------
def page_crosswalk(out: Path) -> Path:
    ns_rows = "\n".join(f"| `{p}` | `{ns}` |" for p, ns in X.PREFIXES.items())
    notes = []
    for pfx in ["crm", "time", "prov", "geo", "dcat", "dcterms", "skos",
                "samian", "lado", "pleiades", "owl", "xsd"]:
        if pfx in T.CROSSWALK_NOTES:
            notes.append(f"### `{pfx}` — `{X.PREFIXES[pfx]}`\n\n"
                         f"{T.CROSSWALK_NOTES[pfx]}\n")

    # The repeated CRMdig and CIDOC CRM axioms belong in the chain: without
    # them lado:DatingActivity would visibly stop at D10, and that the chain
    # continues from there to crm:E7_Activity is precisely the claim this
    # table is meant to substantiate.
    direct = {c: list(sup) for c, sup, _l, _d in X.CLASSES}
    for sub, sup in X.EXTERNAL_AXIOMS:
        direct.setdefault(sub, []).append(sup)
    rows = []
    for c, _sup, _l, _d in X.CLASSES:
        paths = subclass_paths(c, direct)
        chains = "<br>".join(
            " → ".join(f"`{qname(t)}`" for t in path) for path in paths)
        rows.append(f"| `{qname(c)}` | {chains} |")
    hierarchy = "\n".join(rows)

    body = f"""# Crosswalk to community standards

Integration into a shared knowledge graph such as the NFDI4Objects graph
depends on a consumer being able to reach our statements through
vocabularies they already understand, without loading LADO first. That is
the purpose of the subclass chain below: **every local class terminates in
a CIDOC CRM class**, and temporal structure is expressed in OWL-Time
rather than in local properties.

That claim is worth checking rather than asserting, because it is easy to
lose. `lado:DatingModel` originally sat beneath `prov:Plan` alone, which
is an external vocabulary but not CIDOC CRM — a CRM-only consumer could
see the datings and not the method that produced them. It now also sits
beneath `crm:E29_Design_or_Procedure`, the CRM class for a documented
procedure.

## Namespaces

| Prefix | Namespace |
|---|---|
{ns_rows}

## Subclass chain into CIDOC CRM

| Local class | Full chain to an external vocabulary |
|---|---|
{hierarchy}

Rows for classes reached through CRMdig continue past the extension into
CIDOC CRM itself, because the axioms that carry them there are restated
in the vocabulary file — see the note under `crmdig` below.

Each row gives the complete path, not just the immediate parent, because
the immediate parent is often another local class and hides where the
chain actually terminates. Where a class has two superclasses the chain
branches and both paths are listed: `lado:FindspotDating` reaches
`crm:E52_Time-Span` on one and `time:ProperInterval` on the other. A
CRM-only consumer sees a time-span, an OWL-Time consumer sees a proper
interval, both are true at once, and neither needs LADO to recognise the
node.

Relations between the entities use CRM properties directly in their
intended sense, rather than local equivalents:

| Relation | Property used |
|---|---|
| Findspot within its site | `crm:P89_falls_within` |
| Findspot to its dating | `crm:P4_has_time-span` |
| Outer bounds of a dating | `crm:P82a_begin_of_the_begin`, `crm:P82b_end_of_the_end` |

The last row exists because typing a node is not the same as making it
readable. Before it was added, a consumer working only in CIDOC CRM could
follow a findspot to its time-span — all 41 of them — and then find the
span empty, because the years hung solely behind OWL-Time. The two CRM
properties carry the interval bounds as `xsd:gYear`, so the dating can be
read without OWL-Time at all.

They are rounded to whole years, as `time:inXSDgYear` is. The exact
position stays in `time:numericPosition`; these two triples are the
bridge into CRM, not the authoritative figure.

{diagram("vocabularies", "Which vocabulary carries what. The local extension exists only where the standards are silent; a solid edge means one of our classes actually hangs from that vocabulary.")}

{diagram("links", "What makes this Linked Data rather than only RDF. The sites are referenced under the URIs archaeology.link already publishes, not re-asserted under new ones.")}

{diagram("hierarchy", "Every path ends in an external vocabulary. That is the whole claim of the crosswalk.")}
## Per-vocabulary notes

{chr(10).join(notes)}
## Which instances carry a CIDOC CRM type

Every class in this vocabulary reaches CIDOC CRM, but that is a weaker
statement than it sounds, because not every node in the graph is an
instance of one of those classes. The honest position:

| Group | CRM type | Why |
|---|---|---|
| Findspots, sites, datings, plot rows, figures, activities, the model | yes | the substance of the export |
| The export and the bundle themselves | yes, via `crmdig:D1_Digital_Object` | reaching `crm:E73_Information_Object` |
| The exporting software | yes, via `crmdig:D14_Software` | likewise |
| `time:Instant`, `time:TimePosition` | no | CIDOC CRM has no class for an interval endpoint as a node; it expresses boundaries as properties of the time-span, which is why `crm:P82a_begin_of_the_begin` and `crm:P82b_end_of_the_end` are supplied |
| `time:TRS` | no | a temporal reference system has no CRM counterpart |
| `prov:Association` blank nodes | no | reification of an association, structural rather than a thing in the world |
| `owl:Class`, `owl:DatatypeProperty`, `owl:ObjectProperty`, `owl:Ontology` | no | the vocabulary itself, not data described by it |

Forcing the last four groups into CIDOC CRM would be worse modelling than
leaving them alone: a reference system is not an `E55 Type`, and an
`owl:Class` is not an `E1 CRM Entity` in any useful sense. What matters
is not that every node carries a CRM type but that a CRM-only consumer
can reach everything it needs, which is what the property bridge above
secures.

## Every instance reaches CIDOC CRM

The rule this export holds to is stricter than it first appears: **every
instance of an application class carries a CIDOC CRM type**, whether
directly or through an extension that is itself anchored in CRM. It is
not enough for the local classes to have CRM superclasses on paper — the
instances have to arrive there.

Properties are exempt. Where an OWL-Time or PROV-O property expresses the
relation better, it is used; only classes are held to the rule.

Two consequences shaped the model. Interval boundaries became
`lado:DatingInstant` and `lado:DatingTimePosition` rather than bare
`time:Instant` and `time:TimePosition` nodes, so that they could be
anchored in `crm:E52_Time-Span` and `crm:E54_Dimension` without asserting
anything about OWL-Time in general. And the PROV qualified-association
pattern was dropped: a reification node is not a thing in the world and
CIDOC CRM has no class for one. The two statements it carried are now
made directly, with `prov:used` and `crm:P33_used_specific_technique`,
which say the same and are valid in both vocabularies.

The rule is checked on every run rather than assumed, because a new class
without a CRM superclass breaks nothing visible and would otherwise go
unnoticed. The bundle builder counts the instances and refuses to write a
file that contains an unanchored one.

## Notes for knowledge-graph integration

Three properties of this export matter for anyone merging it:

**It is additive over published data.** The only statements made about
`samian:loc_ds_*` nodes are an `rdfs:label` and, where present, the
ancient name and Pleiades identifier. No published node is re-typed, and
no geometry is asserted for a place that already has one. A merge cannot
therefore contradict the discovery-site dataset.

**Absence is explicit.** `lado:undefinedMeasure` distinguishes a value
that was computed and found not to exist from one that nobody has
calculated. Without it, the open-world assumption would flatten the two.

**Presentation is separable.** Everything that exists only because a
figure was drawn hangs off `lado:PlotRow` and `lado:Figure`. A consumer
interested solely in the archaeology can ignore both classes and lose
nothing, and — more importantly — will not mistake a drawing convention
for a dating claim.

One caveat inherited from the published data rather than introduced here:
`loc_discoverysite_1.ttl` (2019 release) binds `prov:` to `http://www.w3.org/ns/prov-o/`,
which is not the PROV-O namespace. All six of its provenance predicates
consequently denote nothing. This export uses the correct namespace and
does not reproduce the error, which means the two files disagree about
what `prov:wasGeneratedBy` denotes until the published file is corrected.
"""
    return write(out, "crosswalk.md", body)


# --------------------------------------------------------------------------
def page_statistics(out: Path) -> Path:
    blocks = []
    for heading, formula, sql, note in T.FORMULAS:
        blocks.append(
            f"## {heading}\n\n```\n{formula}\n```\n\n{note}\n\n"
            f"As implemented:\n\n```sql\n{sql}\n```\n")
    body = f"""# The statistical model

Every formula below is implemented in the source query and every quantity
it produces is exported, so that an interval can be recomputed from the
graph without access to the database. This page states them in one place;
the authoritative implementation remains the SQL.

The parameters in force are recorded on `samian:DatingModel_v1` and are
read from the data rather than restated here, so they cannot drift.

{chr(10).join(blocks)}
## Verifying the export

Two identities hold for every row, and checking them confirms that the
exported figures suffice to reconstruct the interval:

```
k     = k_max − (k_max − k_min) · (1 − exp(−n_stamps_die / τ))
width = eff_end − eff_start = 2 · k · σ
```

Against the current data both hold to within the rounding imposed by the
SQL column types — 4.8 × 10⁻⁵ for k, which is stored as `numeric(10,4)`,
and 0.09 years for the width, stored as `numeric(10,1)`.

## Two axes, deliberately not combined

`lado:qInterval` measures how tightly the contributing potter datings
agree. `lado:qRepetition` measures how often the same dies recur, which
indicates deposit character. They are exported separately and never
averaged.

The reason is that a findspot which is not a hoard would otherwise appear
badly dated. Inchtuthil is the standing example: its dating is sound, but
it is not a deposit, and a combined score would drag it down for a
property that has nothing to do with dating quality.

## A caution about the edge measures

`lado:qStart` and `lado:qEnd` divide by a calendar value. Material dated
near the era boundary is therefore penalised for where it sits in the
calendar rather than for any weakness in the evidence. At Amiens the mean
end date is AD 3 and the scatter is 15 years, giving q_end ≈ 0.004 — the
red whisker in the figure records proximity to the era boundary, not a
poor date. `lado:qInterval` divides by an interval width and is free of
this distortion.

## The unexplained filter

The source query excludes rows where `datemax` takes one of the values
{', '.join(str(v) for v in X.EXCLUDED_DATEMAX)}. The reason is not
documented. The filter is not neutral: it removes the affected potters at
every findspot, not at selected ones. It is recorded in the graph as
`lado:excludedDatemax` on the model rather than left silent, so that a
reader can see that a selection was made even though its rationale is
currently unavailable.
"""
    return write(out, "statistics.md", body)


# --------------------------------------------------------------------------
def page_queries(out: Path) -> Path:
    pairs = [("Figure constants", Q.Q_FIGURE),
             ("One row of the figure", Q.Q_ROWS),
             ("Era convention", Q.Q_ERA),
             ("Model parameters", Q.Q_MODEL)]
    blocks = "\n".join(f"## {name}\n\n```sparql\n{q.strip()}\n```\n"
                       for name, q in pairs)
    fields = "\n".join(f"| `{a}` | `{b}` |" for a, b in Q.FIELD_PAIRS)
    cols = "\n".join(f"| `{h}` |" for _x, _a, h, _f in R.TABLE_COLUMNS)
    body = f"""# Queries and the round trip

The figure is rebuilt from the graph by SPARQL alone. Nothing is
hard-coded in the renderers — margins, row height, colour ramp and sort
order are all read from the `lado:Figure` node — so a quantity missing
from the export causes the rebuild to fail rather than to fall back on a
constant.

The queries below are the ones the pipeline runs, reproduced from the
code. They are also written out as standalone `.rq` files in `queries/`
for use against an endpoint.

{blocks}
## Reaching the interval boundaries

The path from a dating to its numeric boundaries runs through the OWL-Time
constructs rather than through a shortcut property:

```sparql
?ts time:hasBeginning/time:inTimePosition/time:numericPosition ?effStart .
?ts time:hasEnd/time:inTimePosition/time:numericPosition       ?effEnd .
```

This is deliberate. A local `lado:startYear` would have been shorter, but
it would be invisible to any consumer reasoning over OWL-Time. As a
property path the standard route costs one line.

## The round trip

After rendering, the pipeline compares the SPARQL results against the
original CSV, field by field, matching rows on site and findspot rather
than on position:

| SPARQL variable | CSV column |
|---|---|
{fields}

The current state is agreement to 0.00 × 10⁰ on every field.

This check is what makes the modelling claim testable. Two different
figures — the classic and the modern rendering — are produced from the
same graph, which means the information genuinely resides in the graph
rather than in either renderer.

## What the value table shows

The modern figure carries a table beside the time axis, covering what the
web application shows only on hover, plus the whisker annotations:

| Column |
|---|
{cols}

A hover popup is unavailable in print and in an SVG appendix. Placing the
values in fixed columns makes them all visible at once, and removes the
collision that occurred when the annotations were positioned against the
whiskers themselves.
"""
    return write(out, "queries.md", body)


# --------------------------------------------------------------------------
def page_bundle(out: Path) -> Path:
    counted = "\n".join(f"| `{qname(c)}` | {lbl} |"
                         for c, lbl in __import__("make_bundle").COUNTED)
    body = f"""# The standalone bundle

`rdf/IPSDatedSites-bundle.ttl` holds the data, the whole vocabulary and a
materialised CIDOC CRM crosswalk in a single file, so that it can be
loaded into a triplestore on its own — the NFDI4Objects knowledge graph in
particular.

## Why the crosswalk is materialised

Subclass axioms alone are not enough. Most triplestores perform no RDFS
entailment by default, and a shared knowledge graph should not be assumed
to. With the axioms present but nothing inferred, this is the result:

```sparql
SELECT (COUNT(DISTINCT ?x) AS ?n) WHERE {{ ?x a crm:E53_Place }}
```

```
0
```

Every findspot is a place by the axioms, yet a consumer querying in CIDOC
CRM — which is the entire purpose of the crosswalk — sees nothing. The
builder therefore computes the transitive closure over `rdfs:subClassOf`
and writes the inferred `rdf:type` triples out explicitly. The axioms are
kept alongside them, so a store that does reason derives nothing new and
nothing conflicts: the materialised triples are exactly what a reasoner
would produce.

Only `rdf:type` over `rdfs:subClassOf` is inferred. No domain or range
inference, no property closure, no `owl:sameAs` propagation — those would
add bulk and embed assumptions the source data do not support.

The closure is computed from the axioms found in the graph rather than
from a hard-coded table, so adding a superclass in the export propagates
into the bundle without a second edit.

{diagram("materialisation", "Solid edge asserted, dashed edges written out by the builder. Without them a CIDOC CRM query returns nothing.")}

The same node in the finished bundle, drawn from the triples:

![Every type one findspot carries](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/types.svg)

<sub>[SVG](https://raw.githubusercontent.com/leiza-rse/IPSDatedSites/main/img/graphs/types.svg) · [GraphViz source](https://github.com/leiza-rse/IPSDatedSites/blob/main/img/graphs/types.dot) — cut from the graph by CONSTRUCT, generated, do not edit.</sub>

{diagram("parity", "The browser emitter is generated where the model is tabular and hand-written where it is a graph shape. What holds the two together is the hash comparison, not the generation.")}
## What the bundle counts

Each of these is reported as a `void:classPartition` in the file's own
self-description:

| Class | Counted as |
|---|---|
{counted}

## Discovery sites are typed here

The incremental export makes no `rdf:type` statement about the published
`samian:loc_ds_*` nodes; it only references them. That is correct for an
export intended to sit alongside `loc_discoverysite_1.ttl`.

A standalone bundle is a different case. Without the published file
present, `crm:P89_falls_within` would point at an untyped node and a query
for places would miss the sites entirely. The builder therefore asserts
`lado:DiscoverySite` on them, which materialises through `lado:Location`
to `crm:E53_Place`.

This is a restatement rather than a new claim: the published file already
types those nodes the same way. Merging the two files was checked
directly, and the bundle adds only what the axioms entail —
`crm:E53_Place` on each site — with no contradiction. Use
`--no-type-sites` to suppress it where the bundle is only ever loaded
together with the published data.

One exception surfaced during that check and is worth recording: of the 32
sites referenced here, `samian:loc_ds_1004709` (Pecio del Guadiaro, a
shipwreck) has **no triples at all** in the 2019 release of
`loc_discoverysite_1.ttl`. The `v_discoverysite` view knows the identifier
but that file does not contain the node — the site postdates the release.
In a merged graph it would be a reference into nothing; in the bundle it
is at least typed and labelled. A regenerated discovery-site export would
close the gap, and nothing here would need to change, because the export
only ever references those nodes.

## Loading it

The file is self-contained Turtle. No imports, no external ontology needs
to be resolved at load time — the CIDOC CRM and OWL-Time terms are used
by URI and their own definitions can be loaded separately if wanted, but
nothing here depends on their presence.

The file describes itself as a `void:Dataset` and a `dcat:Dataset`,
carrying title, issue date, licence and source, and stating in an
`rdfs:comment` how many of its `rdf:type` triples are inferred rather than
asserted.
"""
    return write(out, "bundle.md", body)


def _verification_facts() -> dict:
    """The facts block, if a verification report is on disk."""
    path = ROOT / "data" / "derived" / "verification.json"
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("facts", {})
    except (OSError, json.JSONDecodeError, AttributeError):
        return {}


def epoch_drift_sentence() -> str:
    """The drift figures, read from the run rather than typed in.

    They were written out by hand once and were stale within a fortnight:
    three findspots joined the corpus, the early median moved from 12.2 to
    13.5 years, and the published prose went on saying twelve. Anything a
    check already computes should be read from the check.
    """
    drift = (_verification_facts() or {}).get("epoch_drift")
    if not drift:
        return ("The size of the effect is reported by check (l) of "
                "`py/verify.py` on every run.")

    before = drift["median_width_before_ad100"]
    after = drift["median_width_from_ad100"]
    ratio = after / before if before else 0.0
    return (
        "The size of the effect may be stated plainly. The median interval "
        f"is {before:.1f} years before AD 100 against {after:.1f} years from "
        f"AD 100, a ratio of about one to {ratio:.1f}, on "
        f"{drift['n_before_ad100']} and {drift['n_from_ad100']} findspots "
        f"respectively (Pearson r = {drift['r_width_vs_year']:+.3f} between "
        "interval width and midpoint year). Allard confirmed on 25 August "
        "2026 that naming the ratio is welcome: the imprecision of second- "
        "and third-century dating relative to the first is an unstudied "
        "area, and any quantification of it is worth having. These figures "
        "come from check (l) of the run that produced this page, so they "
        "cannot fall behind the corpus."
    )


def page_open(notes: Path) -> Path:
    body = f"""# Open questions

Recorded here rather than left implicit, because each one would otherwise
surface at review.

## The exclusion filter

The source query drops rows where `datemax` is one of
{', '.join(str(v) for v in X.EXCLUDED_DATEMAX)}. Nobody involved in the
export knows why. Because the filter applies across all findspots rather
than to selected ones, it shifts every derived figure to some unknown
degree. It is exported as `lado:excludedDatemax` so that the selection is
at least visible.

## Findspot identity

Findspots have no key in the database, only a text label, so URIs are
derived from that text. Correcting a label breaks the URI. The data
currently contain *Böckleareal (descruction layer period II)* — a typo for
*destruction* — in exactly such a field. Either it is corrected before
publication or it is left permanently untouched; both are defensible, but
the decision cannot be deferred past the first publication of the URIs.

Confirmed by the domain expert on 25 August 2026, with one correction to the
worry stated here. There is at present no key at findspot level: the relevant
records are selected through `isdate` and `sitecharacter`, and in future
probably through a column better suited to the purpose than those two markers.

That change does **not** put the URIs at risk, as was feared above. What would
move is the *filter*, not the *labels*: the designations of the find
assemblages themselves — *Fosse Gallicanus*, *Hoard* — stay exactly as they
are. URIs derived from the findspot label are therefore stable across the
change, and the request for a dedicated column is a data-modelling improvement
rather than a precondition for publishing them.

What does remain true is that the findspot label, not the site, is the unit
that matters. A site can carry many entries with no findspot designation at
all, and parallel evaluation routines in Samian Research work at findspot level
too. The typo case above is unaffected: correcting a label still breaks its
URI, and that decision is still owed before first publication.

## Era convention

Confirmed as historical: −40 in the database means 40 BC, and the derived
`xsd:gYear` is shifted by one because XSD counts astronomically, so 40 BC
becomes `-0039`. Only the calendar label is shifted. The decimal
`time:numericPosition` keeps the source value on a documented local scale,
`samian:trs_ips_year`, because shifting only negative values would tear
the scale apart at zero and would not be reversible.

One consequence worth flagging: interval ends near the era boundary can
produce `"0000"^^xsd:gYear`. That is astronomically 1 BC and valid under
XSD 1.1 but not under XSD 1.0. A validator working to the older
specification will object, and the affected literal is the rounded
calendar label rather than the authoritative numeric position.

## Resolved by the domain expert, 25 August 2026

Five questions were put to Allard Mees in writing; the answers are recorded
here because each one now constrains the code.

**The provenance of tau.** Its empirical derivation is to be published in
full, not introduced as a convention. The reference findspots are the only
ones dated independently of ceramics, and that is precisely what makes them
the right basis. `lado:calibrationBasis` and `lado:calibratedAgainst` carry
this in the graph.

**Velsen I, and what the calibration actually rests on.** The terminus was
corrected from AD 30 to AD 28 on 25 August 2026. Velsen I is also the one
reference whose independence is not clean: the military base was in operation
until about AD 28, but activity continued on the site until about AD 40, and
admixture from it cannot be ruled out. It is therefore marked contested —
still drawn in the figure, because the reader should see the case, but
excluded from the criterion that fixes tau.

Nothing published depends on that decision. `py/calibrate_tau.py` recomputes
the floor and reports which references set it:

| reference removed | smallest admissible tau |
| --- | --- |
| none | 4.78 |
| Dangstetten | 4.78 |
| Oberaden | 4.78 |
| Velsen I | 4.78 |
| Pompeii | **1.23** |
| Inchtuthil | 4.78 |

Only Pompeii binds. The other four are carried by the rest of the set and
contribute nothing to the number, so removing Velsen I leaves the floor at
4.78 and the published tau at 6 exactly where they were. This is worth stating
plainly rather than leaving implicit: a basis of five ensembles of which four
are non-binding is, arithmetically, a one-ensemble calibration, and the
headroom of 1.22 between the floor and the published value is what the other
four buy. Pompeii's terminus sits 0.2 years inside its interval at tau = 6;
Inchtuthil's, with three stamps, 6.2 years inside.

Velsen I's modelled interval runs AD 12 to AD 32 and does not reach the later
activity at AD 40. That is consistent with an assemblage not visibly pulled
later by admixture, though it is not evidence that none occurred.

**A fixed number of findspots.** There is not going to be one. Samian
Research is a live database: unchecked ensembles will always exist, and
existing ones are declared usable as work proceeds. The publication states
the data as at a given date rather than asserting a count. The Bregenz
exclusion has accordingly been removed from the query, and the retrieval is
pinned in `data/SNAPSHOT.json` instead. Deliberate exclusions remain
possible as a parameter of `py/ips_model.py`.

**Die attribution.** Not a risk: the stamp type is a compulsory field on
data entry in Samian Research, so findspots without one are not expected to
occur. The `k_no_dierecord` watchdog therefore stays as a check on that
expectation rather than as a handler for an anticipated case.

**The 100-year threshold for wide-dated potters.** It stays. Narrowing it
was rejected on archaeological grounds: potters such as Calvus i worked in
more than one production centre — he appears to have moved from La
Graufesenque to Banassac, taking part of his punches with him — and without
chemical-mineralogical analysis a long span cannot be resolved into
displaced vessels, father and son, a single person, or a workshop. The
threshold marks the limit of attainable precision rather than a tuning
knob.

**Arretine chronology against dendrochronology.** To be mentioned as an
observation and left there. No explanation is currently available, the
offset amounts to very few years, and the potter datings are not precise
enough for it to carry the weight of a criticism.

**Why later intervals are wider.** In Allard's words: the absence of
ceramic-independent dated assemblages with stamped samian in the second and
third centuries has led to speculation about late impressions — moulds used
for a very long time in the production of decorated ware (see the
publications of Huld-Zetsche). Such an assumption would call the
possibility of a samian chronology into question altogether. Genuinely
closed assemblages do exist for the second and third centuries, such as the
finds from the Pudding Pan Rock wreck, but they cannot be dated
independently of the ceramics. That absence also makes residuality very
hard to assess for the period; in the first century it appears not to play
a significant role.

{epoch_drift_sentence()}

## Defects in the published discovery-site data (2019 release)

The published file dates from 2019 and is due for regeneration. Three
defects should be addressed when that happens; none was introduced here.

- `prov:` is bound to `http://www.w3.org/ns/prov-o/`, so all six
  provenance predicates in that file denote nothing.
- Pleiades identifiers carry a trailing `.0` inside the URI, leaving all
  280 links unreachable. The `.0` originates in the database column, which
  is why this export casts to integer.
- `foaf:homepage` holds a string containing angle brackets rather than a
  URI.

## The edge quality measures (resolved)

Resolved in SQL v27c. `lado:qStart` and `lado:qEnd` divided by the mean
calendar value, which penalised material dated near the era boundary for
where it sat in the calendar rather than for anything about the evidence.
Both now read `exp(-sigma / referenceLength)` against a fixed length of
20 years, so they no longer depend on epoch.

Recorded here rather than deleted, because the published figure and the
web output were produced with the earlier form. The source query keeps it
as `q_start_legacy` / `q_end_legacy` for reconstructing those figures;
neither is exported, so anything in the graph carries the current
definition.

A second correction was tried and discarded on the way: making `q_end`
relative to the epoch made the drift worse rather than better, r rising
from +0.103 to +0.335. What that showed is that the widening of later
intervals is not an artefact of the quality measure at all — it belongs
in the width of the box, which already carries it through each potter's
own interval. See the epoch-drift check in `py/verify.py`.
"""
    # NOT under docs/. This page is a working list — half-settled
    # questions, defects found in someone else's published data, decisions
    # still waiting on the domain expert. docs/ is the published website
    # and everything in it is addressed to a reader who was not in the
    # room; this is addressed to the two people who were. It stays in the
    # repository, and therefore stays visible to anyone who looks at the
    # repository, but it is no longer part of what the project publishes.
    notes.mkdir(parents=True, exist_ok=True)
    p = notes / "open-questions.md"
    p.write_text(HEADER + "\n" + body.rstrip() + "\n", encoding="utf-8")
    return p



# --------------------------------------------------------------------------
# The companion pages under docs/docu/
# --------------------------------------------------------------------------
# Those four pages are hand-written and stay that way: they are essays with
# their own typography, not generated reference. What is generated is the
# way in. A hand-written index would be one more thing to remember when a
# fifth page appears, and forgetting it is not hypothetical — the stale
# Bregenz count survived in four places for exactly that reason.
#
# The index deliberately carries NO Jekyll front matter. Jekyll only
# templates files that have it, so this stays a static page and can look
# like the essays it lists rather than like the rest of the site.
DOCU_STYLE = """  :root{--ink:#1b2430;--ink-soft:#46525f;--paper:#fbfaf7;--paper-2:#f2efe8;
        --rule:#d9d3c6;--slip:#9e3b26}
  *{box-sizing:border-box}
  body{margin:0;background:var(--paper);color:var(--ink);
       font-family:"Public Sans",system-ui,sans-serif;font-size:16px;
       line-height:1.6;-webkit-font-smoothing:antialiased}
  .wrap{max-width:44rem;margin:0 auto;padding:3rem 1.4rem 4rem}
  .kicker{font-family:"IBM Plex Mono",monospace;font-size:.73rem;
          letter-spacing:.16em;text-transform:uppercase;color:var(--slip)}
  h1{font-family:Spectral,Georgia,serif;font-weight:600;
     font-size:clamp(1.7rem,3.6vw,2.4rem);margin:.5rem 0 .8rem}
  p.lede{color:var(--ink-soft);margin:0 0 2rem}
  ul.pages{list-style:none;margin:0;padding:0}
  ul.pages li{border-top:1px solid var(--rule);padding:1rem 0}
  ul.pages a{font-family:Spectral,Georgia,serif;font-size:1.12rem;
             color:var(--ink);text-decoration:none}
  ul.pages a:hover{color:var(--slip);text-decoration:underline}
  ul.pages .file{display:block;font-family:"IBM Plex Mono",monospace;
                 font-size:.74rem;color:var(--ink-soft);margin-top:.2rem}
  .back{margin-top:2.5rem;border-top:1px solid var(--rule);
        padding-top:1rem;font-size:.9rem;color:var(--ink-soft)}
  .back a{color:var(--slip)}"""

DOCU_LEDE = (
    "Longer companion pieces to the generated reference: the statistics "
    "written out in full, a walk through the SQL that computes them, and "
    "where the data come from. These are written by hand and revised as "
    "the model changes; the pages linked from the site navigation are "
    "generated from the code.")


def docu_title(path: Path) -> str:
    """The <title> of a companion page, minus any dash-separated subtitle."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"<title>(.*?)</title>", text, re.S | re.I)
    if not m:
        return path.stem.replace("_", " ")
    title = unescape(" ".join(m.group(1).split()))
    for sep in ("\u2014", " - "):
        if sep in title:
            return title.split(sep)[0].strip()
    return title


def page_docu_index(out: Path) -> Path:
    docu = out / "docu"
    docu.mkdir(parents=True, exist_ok=True)
    # Sorted, so the output is byte-identical between runs and platforms;
    # docs/ is compared byte for byte in CI.
    pages = sorted(p for p in docu.glob("*.html") if p.name != "index.html")
    items = "\n".join(
        f'    <li><a href="{p.name}">{escape(docu_title(p))}</a>'
        f'<span class="file">{p.name}</span></li>' for p in pages)
    html = f"""<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Method notes &mdash; IPS dated sites</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Spectral:wght@400;600&\
family=Public+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500\
&display=swap" rel="stylesheet">
<style>
{DOCU_STYLE}
</style>
</head>
<body>
<div class="wrap">
  <p class="kicker">IPS dated sites</p>
  <h1>Method notes</h1>
  <p class="lede">{DOCU_LEDE}</p>
  <ul class="pages">
{items}
  </ul>
  <p class="back">&larr; <a href="../">Back to the overview</a></p>
</div>
</body>
</html>
"""
    p = docu / "index.html"
    p.write_text(html, encoding="utf-8")
    return p


# --------------------------------------------------------------------------
def build(out: Path, graph=None, notes: Path | None = None) -> list[Path]:
    # Diagrams first: the pages embed them.
    _DIAGRAMS.clear()
    _DIAGRAMS.update(D.build(out / "diagrams", graph))
    missing = check_coverage()
    if missing:
        raise SystemExit(
            "Undocumented terms — add them to py/ips_docs_text.py:\n  "
            + "\n  ".join(missing))
    out.mkdir(parents=True, exist_ok=True)
    return [page_index(out), page_model(out), page_vocabulary(out),
            page_crosswalk(out), page_statistics(out), page_queries(out),
            page_bundle(out), page_docu_index(out),
            page_open(notes or (ROOT / "notes"))]


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/*.md")
    ap.add_argument("--out", type=Path, default=ROOT / "docs")
    args = ap.parse_args()
    for p in build(args.out):
        print("  ", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
