"""
IPS Dated Sites — documentation generator
=========================================

Writes docs/*.md. Nothing here is hand-maintained prose about structure:
every class, property, namespace, figure constant and query is read out of
the code at generation time, so a change to the export shows up in the
documentation on the next run rather than drifting away from it.

Three sources are combined:

    ips_rdf_export   CLASSES, OBJ_PROPS, DATA_PROPS, PREFIXES,
                     FIGURE_CONSTANTS, EXCLUDED_DATEMAX, KEY_ALGORITHM
    ips_sparql       the SPARQL queries, verbatim
    ips_docs_text    the English prose, which also feeds rdfs:comment@en

The generator FAILS if a class or property exists in the code without an
entry in TERM_DOCS. Adding a property therefore forces a decision about
how it is described, instead of letting it appear undocumented.

Run via  python py/main.py  (step 5), or on its own:

    python py/make_docs.py --out docs
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import ips_docs_text as T
import ips_rdf_export as X
import ips_render as R
import ips_sparql as Q

ROOT = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
def local(term) -> str:
    """Local name of a URIRef."""
    s = str(term)
    return s.split("#")[-1] if "#" in s else s.rsplit("/", 1)[-1]


def qname(term) -> str:
    """Prefixed name, using the export's own prefix map."""
    s = str(term)
    for pfx, ns in X.PREFIXES.items():
        if s.startswith(str(ns)):
            return f"{pfx}:{s[len(str(ns)):]}"
    return f"<{s}>"


def doc(term) -> str:
    return T.TERM_DOCS.get(local(term), "")


def check_coverage() -> list[str]:
    """Every term in the code must be documented."""
    missing = []
    for cls, *_ in X.CLASSES:
        if local(cls) not in T.TERM_DOCS:
            missing.append(f"class {local(cls)}")
    for prop, *_ in X.OBJ_PROPS + X.DATA_PROPS:
        if local(prop) not in T.TERM_DOCS:
            missing.append(f"property {local(prop)}")
    for pfx in X.PREFIXES:
        if pfx not in T.CROSSWALK_NOTES:
            missing.append(f"namespace {pfx}")
    return missing


HEADER = ("<!-- Generated by py/make_docs.py — do not edit by hand.\n"
          "     The structure is read from the code; the prose lives in\n"
          "     py/ips_docs_text.py. Edit those, then re-run the pipeline. -->\n")


def write(out: Path, name: str, body: str) -> Path:
    p = out / name
    p.write_text(HEADER + "\n" + body.rstrip() + "\n", encoding="utf-8")
    return p


# --------------------------------------------------------------------------
def page_index(out: Path) -> Path:
    n_cls = len(X.CLASSES)
    n_obj = len(X.OBJ_PROPS)
    n_dat = len(X.DATA_PROPS)
    body = f"""# Findspot datings as linked data

How the dating of archaeological findspots by samian potters' stamps is
modelled as RDF, and why each decision was taken.

The source is a single query over the Samian Research / IPS database, one
row per findspot. The export turns each row into a small graph built on
CIDOC CRM, OWL-Time, PROV-O and the local LADO vocabulary, and a companion
step reconstructs the published figure from that graph alone using SPARQL.
That reconstruction is the test of the modelling: if a quantity the figure
needs is missing from the graph, the round trip fails rather than quietly
substituting a default.

## Pages

| Page | Contents |
|---|---|
| [Model](model.md) | The three layers, URI strategy, and the treatment of missing values |
| [Vocabulary](vocabulary.md) | The {n_cls} classes and {n_obj + n_dat} properties minted here |
| [Crosswalk](crosswalk.md) | Mapping to CIDOC CRM, OWL-Time, GeoSPARQL, PROV-O, DCAT and SKOS |
| [Statistics](statistics.md) | The formulas behind the intervals, as implemented in SQL |
| [Queries](queries.md) | The SPARQL used to rebuild the figure, and the round-trip check |
| [Bundle](bundle.md) | The standalone file for a triplestore, and why the crosswalk is materialised |
| [Open questions](open-questions.md) | What remains unresolved and why it matters |

## The shape of it in one paragraph

A findspot (`lado:Findspot`, beneath `crm:E53_Place`) falls within a
published discovery site. Its dating (`lado:FindspotDating`, beneath both
`crm:E52_Time-Span` and `time:ProperInterval`) hangs off it and carries the
computed interval together with every quantity needed to recompute that
interval. The presentation layer sits apart: a `lado:PlotRow` renders the
dating and carries the whiskers, which the method documentation classes as
visual only. Provenance runs through PROV-O, with the model parameters
stated once on a `prov:Plan` rather than repeated on each row.

## Regenerating

These pages are generated. Running the pipeline rewrites them:

```
python py/main.py
```

Structure comes from the code itself — classes, properties, namespaces,
figure constants and queries are read at generation time. The English
prose lives in `py/ips_docs_text.py`, which also supplies the English
`rdfs:comment` on every term in the ontology, so a definition cannot be
correct in the documentation and stale in the RDF. The generator refuses
to run if a class or property in the code has no entry there.

*Generated {date.today().isoformat()} from {n_cls} classes, {n_obj} object
properties and {n_dat} datatype properties.*
"""
    return write(out, "index.md", body)


# --------------------------------------------------------------------------
def page_model(out: Path) -> Path:
    rows = "\n".join(f"| `{c}` | `{s}` | `{p}` |"
                     for c, s, p in T.COLUMN_MAP)
    consts = "\n".join(
        f"| `lado:{k}` | `{v[0]}` | {T.TERM_DOCS.get(k, '')} |"
        for k, v in X.FIGURE_CONSTANTS.items())
    body = f"""# The model

## Three layers, kept apart

The export separates what is in the world, what we claim about it, and
what the drawing does. The separation is not tidiness for its own sake: it
determines what a SPARQL query picks up.

### 1 — Place and findspot

```
samian:loc_ds_<id>          already published, referenced only
samian:fs_<id>_<hash>       lado:Findspot, crm:P89_falls_within the site
```

The discovery site is not re-minted. `the_id` from the `v_discoverysite`
join is the `dc:identifier` of an already published node, and all 3,879 of
those identifiers match their URI suffix exactly, so the URI can be
constructed directly with no lookup table. This export adds an
`rdfs:label` and, where present, the ancient name and Pleiades identifier;
it does not re-type the node or restate what the published file already
says.

The findspot is new. It exists because a site may carry several findspots
with different dates — Bregenz has six — and hanging six time-spans
directly off one place would lose which is which.

### 2 — The dating

```
samian:ts_<id>_<hash>       lado:FindspotDating
                            -> crm:E52_Time-Span, time:ProperInterval
```

Carries the interval boundaries as OWL-Time instants, and with them every
quantity needed to recompute the interval: sigma, k, the stamp count with
die attribution, the die count, the repetition, and both quality axes. The
identity `width = 2·k·σ` can be verified from the exported figures alone,
which is the point of exporting them.

### 3 — Presentation

```
samian:plotrow_<id>_<hash>  lado:PlotRow, lado:renders the dating
samian:fig_<name>           lado:Figure, constants of the drawing
```

The whiskers live here rather than on the time-span. The method
documentation describes the edge dispersion as visual only — it measures
the scatter of the interval edges, whereas the box is built from the
scatter of the midpoints, so the whisker does not continue the box in any
statistical sense. Attaching it to the dating would assert that it does.

The figure constants sit on a single node instead of being repeated on
each of the rows, because they describe the drawing and not the findspots.

| Constant | Value | Meaning |
|---|---|---|
{consts}

## Where each column goes

| SQL column | Subject | Predicate |
|---|---|---|
{rows}

## URIs

Findspot fragments are built as `{X.KEY_ALGORITHM}`. The recipe is
recorded in the graph as `lado:identifierScheme`, because any further
implementation — the planned JavaScript port in particular — must
reproduce it character for character. The Unicode normalisation step is
not cosmetic: if the source yields `ö` once as U+00F6 and once as
`o`+U+0308, the two forms hash differently and one findspot becomes two.
The export checks for collisions and stops rather than silently merging
two findspots that hash alike.

A hash does not make the URI stable. If someone corrects a findspot name,
the hash changes exactly as a readable slug would; it simply changes
invisibly. The readable slug is therefore retained as `skos:notation` so
that a broken link remains diagnosable. There is a live example in the
data: one findspot is recorded as *Böckleareal (descruction layer period
II)*, a typo for *destruction*, sitting in a field from which URIs are
minted.

Time-span URIs are deliberately not versioned. They denote the current
dating of a findspot, so their values change when the source data change.
What is citable is the dated dataset node, which carries `dcterms:issued`
and `owl:versionInfo`; every dating points at it with
`prov:wasDerivedFrom`.

## Missing values

Where a value cannot be computed, the triple is omitted — never replaced
by zero or by 0.5. A fallback of 0.5 would be indistinguishable from a
measured 0.5, which is reachable, and the source query's `COALESCE`
wrappers were removed for that reason.

Omission alone is ambiguous, because under the open-world assumption a
missing triple only means unknown. The export therefore states the absence
explicitly:

```turtle
samian:ts_1000080_a1b2c3 lado:undefinedMeasure lado:qInterval .
```

The figure reads this as its third state: a grey box rather than a
coloured one. If 0.5 were exported instead, anyone reconstructing the
figure from the graph would draw a yellow-green box where the original
draws grey — the fallback would make the figure irreproducible.

In the current data no measure is undefined; all {len(T.COLUMN_MAP)}
mapped columns are populated across every row.
"""
    return write(out, "model.md", body)


# --------------------------------------------------------------------------
def page_vocabulary(out: Path) -> Path:
    cls_rows = []
    for cls, supers, label, _de in X.CLASSES:
        sup = ", ".join(f"`{qname(s)}`" for s in supers)
        cls_rows.append(f"### `{qname(cls)}`\n\n"
                        f"*{label}* — subclass of {sup}\n\n{doc(cls)}\n")

    obj_rows = "\n".join(
        f"| `{qname(p)}` | `{qname(d)}` | `{qname(r)}` | {doc(p)} |"
        for p, d, r, _l, _c in X.OBJ_PROPS)

    def prop_table(props):
        return "\n".join(
            f"| `{qname(p)}` | `{qname(r)}` | {doc(p)} |"
            for p, d, r, _l, _c in props)

    by_domain: dict[str, list] = {}
    for entry in X.DATA_PROPS:
        by_domain.setdefault(qname(entry[1]), []).append(entry)

    sections = []
    for dom in sorted(by_domain):
        sections.append(f"### Properties of `{dom}`\n\n"
                        f"| Property | Range | Definition |\n|---|---|---|\n"
                        f"{prop_table(by_domain[dom])}\n")

    body = f"""# Vocabulary

The classes and properties minted for this export, all in the LADO
namespace `{X.LADO}`. Everything below is read from the code at generation
time; the definitions are the same strings that appear as English
`rdfs:comment` in `rdf/lado_dating_extension.ttl`.

Nothing here duplicates a term that CIDOC CRM or OWL-Time already
provides. Where a standard term exists it is used directly — see the
[crosswalk](crosswalk.md).

## Classes

{chr(10).join(cls_rows)}
## Object properties

| Property | Domain | Range | Definition |
|---|---|---|---|
{obj_rows}

## Datatype properties

{chr(10).join(sections)}
"""
    return write(out, "vocabulary.md", body)


# --------------------------------------------------------------------------
def page_crosswalk(out: Path) -> Path:
    ns_rows = "\n".join(f"| `{p}` | `{ns}` |" for p, ns in X.PREFIXES.items())
    notes = []
    for pfx in ["crm", "time", "prov", "geo", "dcat", "dcterms", "skos",
                "samian", "lado", "pleiades", "owl", "xsd"]:
        if pfx in T.CROSSWALK_NOTES:
            notes.append(f"### `{pfx}` — `{X.PREFIXES[pfx]}`\n\n"
                         f"{T.CROSSWALK_NOTES[pfx]}\n")

    hierarchy = "\n".join(
        f"| `{qname(c)}` | {', '.join(f'`{qname(s)}`' for s in sup)} |"
        for c, sup, _l, _d in X.CLASSES)

    body = f"""# Crosswalk to community standards

Integration into a shared knowledge graph such as the NFDI4Objects graph
depends on a consumer being able to reach our statements through
vocabularies they already understand, without loading LADO first. That is
the purpose of the subclass chain below: every local class terminates in a
CIDOC CRM class, and temporal structure is expressed in OWL-Time rather
than in local properties.

## Namespaces

| Prefix | Namespace |
|---|---|
{ns_rows}

## Subclass chain into CIDOC CRM

| Local class | Direct superclasses |
|---|---|
{hierarchy}

Reading the chain: `lado:FindspotDating` → `lado:DatedTimeSpan` →
`crm:E52_Time-Span` and `time:ProperInterval`. A CRM-only consumer sees a
time-span; an OWL-Time consumer sees a proper interval; both are true
simultaneously, and neither needs LADO to recognise the node.

Relations between the entities use CRM properties directly in their
intended sense, rather than local equivalents:

| Relation | Property used |
|---|---|
| Findspot within its site | `crm:P89_falls_within` |
| Findspot to its dating | `crm:P4_has_time-span` |

## Per-vocabulary notes

{chr(10).join(notes)}
## Notes for knowledge-graph integration

Three properties of this export matter for anyone merging it:

**It is additive over published data.** The only statements made about
`samian:loc_ds_*` nodes are an `rdfs:label` and, where present, the
ancient name and Pleiades identifier. No published node is re-typed, and
no geometry is asserted for a place that already has one. A merge cannot
therefore contradict the discovery-site dataset.

**Absence is explicit.** `lado:undefinedMeasure` distinguishes a value
that was computed and found not to exist from one that nobody has
calculated. Without it, the open-world assumption would flatten the two.

**Presentation is separable.** Everything that exists only because a
figure was drawn hangs off `lado:PlotRow` and `lado:Figure`. A consumer
interested solely in the archaeology can ignore both classes and lose
nothing, and — more importantly — will not mistake a drawing convention
for a dating claim.

One caveat inherited from the published data rather than introduced here:
`loc_discoverysite_1.ttl` binds `prov:` to `http://www.w3.org/ns/prov-o/`,
which is not the PROV-O namespace. All six of its provenance predicates
consequently denote nothing. This export uses the correct namespace and
does not reproduce the error, which means the two files disagree about
what `prov:wasGeneratedBy` denotes until the published file is corrected.
"""
    return write(out, "crosswalk.md", body)


# --------------------------------------------------------------------------
def page_statistics(out: Path) -> Path:
    blocks = []
    for heading, formula, sql, note in T.FORMULAS:
        blocks.append(
            f"## {heading}\n\n```\n{formula}\n```\n\n{note}\n\n"
            f"As implemented:\n\n```sql\n{sql}\n```\n")
    body = f"""# The statistical model

Every formula below is implemented in the source query and every quantity
it produces is exported, so that an interval can be recomputed from the
graph without access to the database. This page states them in one place;
the authoritative implementation remains the SQL.

The parameters in force are recorded on `samian:DatingModel_v1` and are
read from the data rather than restated here, so they cannot drift.

{chr(10).join(blocks)}
## Verifying the export

Two identities hold for every row, and checking them confirms that the
exported figures suffice to reconstruct the interval:

```
k     = k_max − (k_max − k_min) · (1 − exp(−n_stamps_die / τ))
width = eff_end − eff_start = 2 · k · σ
```

Against the current data both hold to within the rounding imposed by the
SQL column types — 4.8 × 10⁻⁵ for k, which is stored as `numeric(10,4)`,
and 0.09 years for the width, stored as `numeric(10,1)`.

## Two axes, deliberately not combined

`lado:qInterval` measures how tightly the contributing potter datings
agree. `lado:qRepetition` measures how often the same dies recur, which
indicates deposit character. They are exported separately and never
averaged.

The reason is that a findspot which is not a hoard would otherwise appear
badly dated. Inchtuthil is the standing example: its dating is sound, but
it is not a deposit, and a combined score would drag it down for a
property that has nothing to do with dating quality.

## A caution about the edge measures

`lado:qStart` and `lado:qEnd` divide by a calendar value. Material dated
near the era boundary is therefore penalised for where it sits in the
calendar rather than for any weakness in the evidence. At Amiens the mean
end date is AD 3 and the scatter is 15 years, giving q_end ≈ 0.004 — the
red whisker in the figure records proximity to the era boundary, not a
poor date. `lado:qInterval` divides by an interval width and is free of
this distortion.

## The unexplained filter

The source query excludes rows where `datemax` takes one of the values
{', '.join(str(v) for v in X.EXCLUDED_DATEMAX)}. The reason is not
documented. The filter is not neutral: it removes the affected potters at
every findspot, not at selected ones. It is recorded in the graph as
`lado:excludedDatemax` on the model rather than left silent, so that a
reader can see that a selection was made even though its rationale is
currently unavailable.
"""
    return write(out, "statistics.md", body)


# --------------------------------------------------------------------------
def page_queries(out: Path) -> Path:
    pairs = [("Figure constants", Q.Q_FIGURE),
             ("One row of the figure", Q.Q_ROWS),
             ("Era convention", Q.Q_ERA),
             ("Model parameters", Q.Q_MODEL)]
    blocks = "\n".join(f"## {name}\n\n```sparql\n{q.strip()}\n```\n"
                       for name, q in pairs)
    fields = "\n".join(f"| `{a}` | `{b}` |" for a, b in Q.FIELD_PAIRS)
    cols = "\n".join(f"| `{h}` |" for _x, _a, h, _f in R.TABLE_COLUMNS)
    body = f"""# Queries and the round trip

The figure is rebuilt from the graph by SPARQL alone. Nothing is
hard-coded in the renderers — margins, row height, colour ramp and sort
order are all read from the `lado:Figure` node — so a quantity missing
from the export causes the rebuild to fail rather than to fall back on a
constant.

The queries below are the ones the pipeline runs, reproduced from the
code. They are also written out as standalone `.rq` files in `queries/`
for use against an endpoint.

{blocks}
## Reaching the interval boundaries

The path from a dating to its numeric boundaries runs through the OWL-Time
constructs rather than through a shortcut property:

```sparql
?ts time:hasBeginning/time:inTimePosition/time:numericPosition ?effStart .
?ts time:hasEnd/time:inTimePosition/time:numericPosition       ?effEnd .
```

This is deliberate. A local `lado:startYear` would have been shorter, but
it would be invisible to any consumer reasoning over OWL-Time. As a
property path the standard route costs one line.

## The round trip

After rendering, the pipeline compares the SPARQL results against the
original CSV, field by field, matching rows on site and findspot rather
than on position:

| SPARQL variable | CSV column |
|---|---|
{fields}

The current state is agreement to 0.00 × 10⁰ on every field.

This check is what makes the modelling claim testable. Two different
figures — the classic and the modern rendering — are produced from the
same graph, which means the information genuinely resides in the graph
rather than in either renderer.

## What the value table shows

The modern figure carries a table beside the time axis, covering what the
web application shows only on hover, plus the whisker annotations:

| Column |
|---|
{cols}

A hover popup is unavailable in print and in an SVG appendix. Placing the
values in fixed columns makes them all visible at once, and removes the
collision that occurred when the annotations were positioned against the
whiskers themselves.
"""
    return write(out, "queries.md", body)


# --------------------------------------------------------------------------
def page_bundle(out: Path) -> Path:
    counted = "\n".join(f"| `{qname(c)}` | {lbl} |"
                         for c, lbl in __import__("make_bundle").COUNTED)
    body = f"""# The standalone bundle

`rdf/IPSDatedSites-bundle.ttl` holds the data, the whole vocabulary and a
materialised CIDOC CRM crosswalk in a single file, so that it can be
loaded into a triplestore on its own — the NFDI4Objects knowledge graph in
particular.

## Why the crosswalk is materialised

Subclass axioms alone are not enough. Most triplestores perform no RDFS
entailment by default, and a shared knowledge graph should not be assumed
to. With the axioms present but nothing inferred, this is the result:

```sparql
SELECT (COUNT(DISTINCT ?x) AS ?n) WHERE {{ ?x a crm:E53_Place }}
```

```
0
```

Every findspot is a place by the axioms, yet a consumer querying in CIDOC
CRM — which is the entire purpose of the crosswalk — sees nothing. The
builder therefore computes the transitive closure over `rdfs:subClassOf`
and writes the inferred `rdf:type` triples out explicitly. The axioms are
kept alongside them, so a store that does reason derives nothing new and
nothing conflicts: the materialised triples are exactly what a reasoner
would produce.

Only `rdf:type` over `rdfs:subClassOf` is inferred. No domain or range
inference, no property closure, no `owl:sameAs` propagation — those would
add bulk and embed assumptions the source data do not support.

The closure is computed from the axioms found in the graph rather than
from a hard-coded table, so adding a superclass in the export propagates
into the bundle without a second edit.

## What the bundle counts

Each of these is reported as a `void:classPartition` in the file's own
self-description:

| Class | Counted as |
|---|---|
{counted}

## Discovery sites are typed here

The incremental export makes no `rdf:type` statement about the published
`samian:loc_ds_*` nodes; it only references them. That is correct for an
export intended to sit alongside `loc_discoverysite_1.ttl`.

A standalone bundle is a different case. Without the published file
present, `crm:P89_falls_within` would point at an untyped node and a query
for places would miss the sites entirely. The builder therefore asserts
`lado:DiscoverySite` on them, which materialises through `lado:Location`
to `crm:E53_Place`.

This is a restatement rather than a new claim: the published file already
types those nodes the same way. Merging the two files was checked
directly, and the bundle adds only what the axioms entail —
`crm:E53_Place` on each site — with no contradiction. Use
`--no-type-sites` to suppress it where the bundle is only ever loaded
together with the published data.

One exception surfaced during that check and is worth recording: of the 32
sites referenced here, `samian:loc_ds_1004709` (Pecio del Guadiaro, a
shipwreck) has **no triples at all** in `loc_discoverysite_1.ttl`. The
`v_discoverysite` view knows the identifier but the published linked-data
file does not contain the node. In a merged graph that would be a
reference into nothing; in the bundle it is at least typed and labelled.

## Loading it

The file is self-contained Turtle. No imports, no external ontology needs
to be resolved at load time — the CIDOC CRM and OWL-Time terms are used
by URI and their own definitions can be loaded separately if wanted, but
nothing here depends on their presence.

The file describes itself as a `void:Dataset` and a `dcat:Dataset`,
carrying title, issue date, licence and source, and stating in an
`rdfs:comment` how many of its `rdf:type` triples are inferred rather than
asserted.
"""
    return write(out, "bundle.md", body)


def page_open(out: Path) -> Path:
    body = f"""# Open questions

Recorded here rather than left implicit, because each one would otherwise
surface at review.

## The exclusion filter

The source query drops rows where `datemax` is one of
{', '.join(str(v) for v in X.EXCLUDED_DATEMAX)}. Nobody involved in the
export knows why. Because the filter applies across all findspots rather
than to selected ones, it shifts every derived figure to some unknown
degree. It is exported as `lado:excludedDatemax` so that the selection is
at least visible.

## Findspot identity

Findspots have no key in the database, only a text label, so URIs are
derived from that text. Correcting a label breaks the URI. The data
currently contain *Böckleareal (descruction layer period II)* — a typo for
*destruction* — in exactly such a field. Either it is corrected before
publication or it is left permanently untouched; both are defensible, but
the decision cannot be deferred past the first publication of the URIs.

## Era convention

Confirmed as historical: −40 in the database means 40 BC, and the derived
`xsd:gYear` is shifted by one because XSD counts astronomically, so 40 BC
becomes `-0039`. Only the calendar label is shifted. The decimal
`time:numericPosition` keeps the source value on a documented local scale,
`samian:trs_ips_year`, because shifting only negative values would tear
the scale apart at zero and would not be reversible.

One consequence worth flagging: interval ends near the era boundary can
produce `"0000"^^xsd:gYear`. That is astronomically 1 BC and valid under
XSD 1.1 but not under XSD 1.0. A validator working to the older
specification will object, and the affected literal is the rounded
calendar label rather than the authoritative numeric position.

## Defects in the published discovery-site data

Three, none introduced here, all worth correcting at source:

- `prov:` is bound to `http://www.w3.org/ns/prov-o/`, so all six
  provenance predicates in that file denote nothing.
- Pleiades identifiers carry a trailing `.0` inside the URI, leaving all
  280 links unreachable. The `.0` originates in the database column, which
  is why this export casts to integer.
- `foaf:homepage` holds a string containing angle brackets rather than a
  URI.

## The edge quality measures

`lado:qStart` and `lado:qEnd` are distorted by proximity to the calendar
origin. They are exported because they drive whisker colour in the
published figure and removing them would break comparability with the web
output, but they should not be presented as quality measures without that
caveat. `lado:qInterval` is unaffected and is the measure to prefer.
"""
    return write(out, "open-questions.md", body)


# --------------------------------------------------------------------------
def build(out: Path) -> list[Path]:
    missing = check_coverage()
    if missing:
        raise SystemExit(
            "Undocumented terms — add them to py/ips_docs_text.py:\n  "
            + "\n  ".join(missing))
    out.mkdir(parents=True, exist_ok=True)
    return [page_index(out), page_model(out), page_vocabulary(out),
            page_crosswalk(out), page_statistics(out), page_queries(out),
            page_bundle(out), page_open(out)]


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/*.md")
    ap.add_argument("--out", type=Path, default=ROOT / "docs")
    args = ap.parse_args()
    for p in build(args.out):
        print("  ", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
